name = "distribute"
version = "3.0.0"
description = "Typed distributed messaging for Gleam on the BEAM."
licences = ["MIT"]
repository = { type = "github", user = "lupodevelop", repo = "distribute" }
links = [
  { title = "GitHub", href = "https://github.com/lupodevelop/distribute" },
]

target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
